import 'category_details.dart';
import 'discount.dart';
import 'models.dart';

final mockProducts = <Product>[
  const Product(
    id: '1',
    image: 'https://via.placeholder.com/150',
    vendorPrice: 10,
    vendeasePrice: 8,
    marketPrice: 12,
    discountDeleted: false,
    deleted: false,
    name: 'Product 1',
    categoryId: 'category1',
    subCategoryId: 'subcategory1',
    description: 'This is a test product',
    discount: Discount(
      discountType: 'percentage',
      discountValue: 20,
      id: 'discount1',
    ),
    weight: 100,
    weightUnit: 'kg',
    countryCode: 'NG',
    cityCode: 'Lagos',
    ownerType: 'vendor',
    owner: 'John Doe',
    createdAt: '2022-01-01T12:00:00Z',
    updatedAt: '2022-01-01T12:00:00Z',
    volume: 0,
    categoryDetails: CategoryDetails(
      name: 'Fruits',
      taxExempt: false,
      subCategory: 'Apples',
    ),
  ),
  const Product(
    id: '2',
    image: 'https://via.placeholder.com/150',
    vendorPrice: 15,
    vendeasePrice: 12,
    marketPrice: 18,
    discountDeleted: false,
    deleted: false,
    name: 'Product 2',
    categoryId: 'category2',
    subCategoryId: 'subcategory2',
    description: 'This is a test product',
    discount: Discount(
      discountType: 'percentage',
      discountValue: 20,
      id: 'discount2',
    ),
    weight: 200,
    weightUnit: 'kg',
    countryCode: 'NG',
    cityCode: 'Lagos',
    ownerType: 'vendor',
    owner: 'Jane Doe',
    createdAt: '2022-01-01T12:00:00Z',
    updatedAt: '2022-01-01T12:00:00Z',
    volume: 0,
    categoryDetails: CategoryDetails(
      name: 'Clothes',
      taxExempt: true,
      subCategory: 'Shirts',
    ),
  ),
];
